name: stars_hwdi_dbt
version: "1.0.0"
config-version: 2

profile: stars_hwdi

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  stars_hwdi_dbt:
    +persist_docs:
      relation: true
      columns: true

    staging:
      +materialized: view
      +schema: CORE_STAGING

    silver:
      +materialized: incremental
      +schema: SILVER
      +incremental_strategy: merge

    gold:
      +materialized: table
      +schema: GOLD
